//
// Created by faliszewskii on 27.05.24.
//

#ifndef OPENGL_SANDBOX_RESETSELECTIONEVENT_H
#define OPENGL_SANDBOX_RESETSELECTIONEVENT_H

struct ResetSelectionEvent{};

#endif //OPENGL_SANDBOX_RESETSELECTIONEVENT_H
