//
// Created by faliszewskii on 05.03.24.
//

#ifndef OPENGL_SANDBOX_ENTITYSELECTIONCHANGEDEVENT_H
#define OPENGL_SANDBOX_ENTITYSELECTIONCHANGEDEVENT_H

struct EntitySelectionChangedEvent {

};
#endif //OPENGL_SANDBOX_ENTITYSELECTIONCHANGEDEVENT_H
