//
// Created by faliszewskii on 11.03.24.
//

#ifndef OPENGL_SANDBOX_SELECTIONCHANGEDEVENT_H
#define OPENGL_SANDBOX_SELECTIONCHANGEDEVENT_H

struct SelectionChangedEvent {};

#endif //OPENGL_SANDBOX_SELECTIONCHANGEDEVENT_H
