//
// Created by faliszewskii on 08.04.24.
//

#ifndef OPENGL_SANDBOX_CREATEINTERPOLATEDC2EVENT_H
#define OPENGL_SANDBOX_CREATEINTERPOLATEDC2EVENT_H

struct CreateInterpolatedC2Event {
};
#endif //OPENGL_SANDBOX_CREATEINTERPOLATEDC2EVENT_H
