//
// Created by faliszewskii on 05.03.24.
//

#ifndef OPENGL_SANDBOX_OBJECTCREATIONHANDLER_H
#define OPENGL_SANDBOX_OBJECTCREATIONHANDLER_H

class ObjectCreationHandler {

};

#endif //OPENGL_SANDBOX_OBJECTCREATIONHANDLER_H
